import Foundation

/// The commands the guest is asked to run.
enum AcceptanceScript {
    /// The path the VirtioFS automount tag is expected to produce.
    ///
    /// Expected, not assumed: the script locates the real mount and fails
    /// loudly if it is somewhere else, because confirming this path on the
    /// selected guest build is one of the questions the POC exists to answer.
    static let expectedSharePath = "/Volumes/My Shared Files"

    /// A trivial command that must exit zero.
    ///
    /// Run before the acceptance command so that "the guest is not ready yet"
    /// stays distinguishable from the deliberate non-zero exit that follows.
    static let readinessCommand = "/usr/bin/id -un"

    /// The acceptance command.
    ///
    /// Every value interpolated here is generated by this tool — a UUID, a hex
    /// nonce, a volume name it chose — so none of it is attacker-influenced.
    /// It is still single-quoted, and the whole script is delivered base64-
    /// encoded, so that a marker containing an unexpected character could never
    /// change the script's meaning.
    static func acceptanceScript(expectations: RunExpectations, username: String) -> String {
        let share = ShellEscaping.singleQuoted(expectedSharePath)
        let artifactVolume = ShellEscaping.singleQuoted(expectations.artifactVolumeName)
        let artifactPath = ShellEscaping.singleQuoted(
            "/Volumes/\(expectations.artifactVolumeName)"
        )
        let marker = ShellEscaping.singleQuoted(expectations.marker)
        let stdoutToken = ShellEscaping.singleQuoted(expectations.stdoutToken)
        let stderrToken = ShellEscaping.singleQuoted(expectations.stderrToken)

        return """
        set -eu

        share=\(share)
        artifact=\(artifactPath)
        artifact_volume=\(artifactVolume)
        marker=\(marker)

        # The artifact volume is preformatted APFS on a Virtio block device.
        # macOS automounts external volumes via diskarbitrationd in a console
        # user session, so with nobody logged in it may never appear. Mounting
        # by volume name makes the run independent of that behaviour.
        if [ ! -d "$artifact" ]; then
            /usr/sbin/diskutil mount "$artifact_volume" >&2
        fi

        # Assert on the real mounts rather than trusting that they appeared.
        test -d "$share"
        test -w "$share"
        test -d "$artifact"
        test -w "$artifact"

        printf '%s\\n' "$marker" > "$share/vre-result.txt"
        printf '%s\\n' "$marker" > "$artifact/vre-result.txt"
        printf '%s\\n' "$marker" > "$HOME/vre-result.txt"

        # Flush before the host is told the write happened. Combined with the
        # artifact disk's full synchronisation mode, this removes the ambiguity
        # between "the guest never wrote it" and "the host never flushed it".
        /bin/sync

        printf '%s\\n' \(stdoutToken)
        printf '%s\\n' \(stderrToken) >&2

        # A deliberately non-zero status. Exit 23 proves the harness reports the
        # remote command's own status instead of collapsing anything non-zero
        # into a generic failure. 255 is avoided: OpenSSH reserves it for its
        # own errors, which would make the assertion meaningless.
        exit 23
        """
    }

    /// Diagnostics gathered from the guest when something goes wrong.
    static let diagnosticsScript = """
    echo '--- id'; /usr/bin/id || true
    echo '--- mounts'; /sbin/mount || true
    echo '--- volumes'; /bin/ls -la /Volumes || true
    echo '--- diskutil list'; /usr/sbin/diskutil list || true
    echo '--- remote login'; /usr/sbin/systemsetup -getremotelogin 2>/dev/null || true
    echo '--- sshd access group'; /usr/bin/dscl . -read /Groups/com.apple.access_ssh 2>/dev/null || true
    echo '--- admin membership'; /usr/sbin/dseditgroup -o checkmember -m "$(/usr/bin/id -un)" admin 2>&1 || true
    echo '--- uptime'; /usr/bin/uptime || true
    """

    /// A graceful shutdown requested from inside the guest.
    ///
    /// `sudo -S` reads the password from standard input, so it never appears in
    /// the guest's process list. This is only used when Virtualization's own
    /// `requestStop` has already failed or timed out.
    static let shutdownCommand = "/usr/bin/sudo -S -p '' /sbin/shutdown -h now"
}
