import Foundation

enum CloudInitSeed {
    static let volumeLabel = "CIDATA"

    static let shareTag = "viv"
    static let shareMountPath = "/mnt/viv"

    static func write(
        to destination: URL,
        request: ProvisioningRequest,
        publicKey: String
    ) async throws {
        let staging = destination.deletingLastPathComponent()
            .appendingPathComponent("seed-staging-\(UUID().uuidString)")
        defer { try? FileManager.default.removeItem(at: staging) }

        do {
            try FileManager.default.createDirectory(at: staging, withIntermediateDirectories: true)
            try Data(metaData(request: request).utf8)
                .write(to: staging.appendingPathComponent("meta-data"), options: .atomic)
            try Data(userData(request: request, publicKey: publicKey).utf8)
                .write(to: staging.appendingPathComponent("user-data"), options: .atomic)
        } catch {
            throw VivError(
                .provisioning,
                "Cannot stage the cloud-init seed under \(staging.path).",
                underlying: error
            )
        }

        try? FileManager.default.removeItem(at: destination)

        try await ProcessRunner.runChecked(
            "/usr/bin/hdiutil",
            ["makehybrid", "-iso", "-joliet",
             "-default-volume-name", volumeLabel,
             "-o", destination.path,
             staging.path],
            timeout: .seconds(120),
            stage: .provisioning,
            inspectionHints: ["ls -la \(staging.path)"]
        )
        log.info("Cloud-init seed written to \(destination.path).")
    }

    static func metaData(request: ProvisioningRequest) -> String {
        """
        instance-id: \(yaml(request.runID))
        local-hostname: \(yaml(request.hostname))
        """
    }

    static func userData(request: ProvisioningRequest, publicKey: String) -> String {
        let credentials = request.credentials
        return """
        #cloud-config
        # Generated by Vivarium for run \(request.runID). Read once, by one guest.

        preserve_hostname: false
        disable_root: true
        # The guest keeps its distribution's own refusal of password logins. The
        # host authenticates with the key below and has no password to offer.
        ssh_pwauth: false

        users:
          - name: \(yaml(credentials.username))
            gecos: \(yaml(credentials.fullName))
            # No password exists for this account, so none can be guessed and
            # none has to be stored anywhere.
            lock_passwd: true
            shell: /bin/bash
            # The account needs to be able to halt the machine, and there is no
            # password for sudo to ask for.
            sudo: "ALL=(ALL) NOPASSWD:ALL"
            groups: [wheel]
            ssh_authorized_keys:
              - \(yaml(publicKey))

        # The image is published at the size it was built; the disk it was
        # cloned onto is larger, and a build with four gigabytes of room is not
        # a developer environment. growpart moves the partition table's idea of
        # the end of the disk, and resize_rootfs grows the filesystem into it.
        growpart:
          mode: auto
          devices: ["/"]
        resize_rootfs: true

        # Nothing is updated or installed here. A run that quietly pulled a
        # different set of packages each morning would not be testing the same
        # thing twice.
        package_update: false
        package_upgrade: false

        # cloud-init's own output goes to the guest's log and to the serial
        # console, which the host is recording. It is the only account of what
        # happened between power-on and sshd, and the only one available at all
        # when the guest never reaches sshd.
        output:
          all: "| tee -a /var/log/cloud-init-output.log /dev/hvc0"

        runcmd:
          - [mkdir, -p, \(yaml(shareMountPath))]
          - [mount, -t, virtiofs, \(yaml(shareTag)), \(yaml(shareMountPath))]

        """
    }

    static func yaml(_ value: String) -> String {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.withoutEscapingSlashes]
        guard let data = try? encoder.encode(value),
              let encoded = String(data: data, encoding: .utf8) else {
            return "\"" + value.replacingOccurrences(of: "\"", with: "\\\"") + "\""
        }
        return encoded
    }
}
