import Foundation

/// How the host proves who it is to the guest.
///
/// Two mechanisms, one per guest operating system, and the difference is not
/// arbitrary. A macOS guest is provisioned by `VZMacGuestProvisioningOptions`,
/// which takes a password and nothing else, so the password is what there is. A
/// Linux guest is provisioned by cloud-init from a seed image that sits in the
/// run's bundle for the life of the guest — so a password in it would be a
/// password written to disk, which is exactly what the macOS path is careful
/// never to do. A public key in the same place is not a secret at all, and it
/// also means the guest keeps its distribution's own posture of refusing
/// password logins over SSH rather than having Vivarium turn that off.
enum GuestAuthentication: Sendable {
    /// Generated for this run, held in this process's memory, and nowhere else.
    case password(String)
    /// An ed25519 key pair generated for this run. The private half is written
    /// into the run's own bundle, mode 0600, and goes when the bundle does; the
    /// public half is what the seed image carries.
    case privateKey(path: URL, publicKey: String)
    /// No credential. A bundle adopted from an earlier invocation has one of
    /// these: the password was never persisted, so it cannot be recovered, and
    /// saying so is better than presenting an empty string as a credential.
    case unavailable
}

/// The provisioned guest account.
struct GuestCredentials: Sendable {
    let fullName: String
    let username: String
    let authentication: GuestAuthentication

    /// Whether this credential can still open a session.
    var isUsable: Bool {
        if case .unavailable = authentication { return false }
        return true
    }

    /// The password, where there is one. Only the shutdown path and the macOS
    /// provisioning options have any business asking.
    var password: String? {
        if case let .password(password) = authentication { return password }
        return nil
    }

    /// How `run.json` records where the credential lives, given that it never
    /// records the credential.
    var storageDescription: String {
        switch authentication {
        case .password:
            return "in-memory only; not persisted"
        case let .privateKey(path, _):
            return "ed25519 private key at \(path.lastPathComponent) in this bundle, mode 0600"
        case .unavailable:
            return "none: this bundle was adopted, and the original credential was not persisted"
        }
    }

    /// What to tell an operator holding a guest open for inspection.
    func inspectionAdvice(username: String, address: String, bundle: URL) -> String {
        switch authentication {
        case .password:
            return """
                The password is generated per run and lives only in this process's \
                memory: it is never printed, logged, or written down, so there is no \
                new SSH session to be had. What is inspectable is the run directory \
                above and any session already open.
                """
        case let .privateKey(path, _):
            return """
                The guest's key pair belongs to this run and goes when the run \
                directory does, so a second session is a command away:

                  ssh -i \(path.path) -o UserKnownHostsFile=\(bundle.appendingPathComponent("ssh_known_hosts").path) \(username)@\(address)
                """
        case .unavailable:
            return "This bundle carries no usable credential, so there is no session to be had."
        }
    }
}

/// The password a macOS guest is provisioned with.
enum GuestPassword {
    /// Generates a password from the system CSPRNG.
    ///
    /// The alphabet excludes characters that macOS account creation has
    /// historically rejected or that would complicate shell handling, and the
    /// length is chosen so the result is well beyond guessing even though the
    /// VM is only reachable on a host-local NAT.
    static func generate() -> String {
        let alphabet = Array("abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789")
        var password = ""
        var bytes = [UInt8](repeating: 0, count: 32)
        let status = SecRandomCopyBytes(kSecRandomDefault, bytes.count, &bytes)
        precondition(status == errSecSuccess, "SecRandomCopyBytes failed with \(status).")
        for byte in bytes {
            password.append(alphabet[Int(byte) % alphabet.count])
        }
        // macOS requires a password that is not trivially weak; a 32-character
        // mixed-case alphanumeric satisfies every policy the installer applies.
        return password
    }
}

/// The key pair a Linux guest is provisioned with.
///
/// Generated by `/usr/bin/ssh-keygen` rather than in-process: OpenSSH's private
/// key container is its own format, and the client that will read the key back
/// is the same OpenSSH, so the tool that writes it is the one guaranteed to
/// agree with it about what it wrote.
enum GuestKeyPair {
    static func generate(at path: URL, comment: String) async throws -> GuestAuthentication {
        // ssh-keygen refuses to overwrite without a prompt, and a prompt on a
        // run nobody is watching is a hang.
        for candidate in [path, path.appendingPathExtension("pub")] {
            try? FileManager.default.removeItem(at: candidate)
        }

        try await ProcessRunner.runChecked(
            "/usr/bin/ssh-keygen",
            ["-q", "-t", "ed25519", "-N", "", "-C", comment, "-f", path.path],
            timeout: .seconds(60),
            stage: .provisioning,
            inspectionHints: ["ls -la \(path.deletingLastPathComponent().path)"]
        )

        let publicKeyURL = path.appendingPathExtension("pub")
        guard let text = try? String(contentsOf: publicKeyURL, encoding: .utf8) else {
            throw VivError(
                .provisioning,
                "ssh-keygen reported success but wrote no public key at \(publicKeyURL.path)."
            )
        }
        let publicKey = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard publicKey.hasPrefix("ssh-ed25519 ") else {
            throw VivError(
                .provisioning,
                "\(publicKeyURL.path) does not look like an ed25519 public key."
            )
        }

        // ssh-keygen already writes 0600, and OpenSSH refuses a key that is not.
        // Asserting it here means a umask or a filesystem that ignored the mode
        // is found now rather than at the first connection.
        let mode = (try? FileManager.default.attributesOfItem(atPath: path.path))?[.posixPermissions]
        if let mode = (mode as? NSNumber)?.uint16Value, mode & 0o077 != 0 {
            throw VivError(
                .provisioning,
                "\(path.path) is mode \(String(mode, radix: 8)); OpenSSH will refuse a private "
                    + "key that others can read."
            )
        }

        return .privateKey(path: path, publicKey: publicKey)
    }
}
